GET http://localhost:3000/testController

###
GET http://localhost:3000/testController/61e123fe138d289abfe5ea80

###
POST http://localhost:3000/testController
Content-Type: application/json

{
    "Name":"Rupna Islam shuva"
}
###
PATCH  http://localhost:3000/testController/61e2791088d508449e9608d1
Content-Type: application/json

{
    "Name":"Faul"
}

###
DELETE http://localhost:3000/testController/61e185f445ed93b746c4177d